python -m lerobot_policy_recap.reinforcement_loop.builds.train.train_recap \
    --output_dir=/home/ubuntu/lerobot_manufex/outputs/recap \
    --policy.push_to_hub=false \
    --dataset.repo_id=/home/ubuntu/lerobot_manufex/datasets/towel_red_sparse_rewards_fast \
    --policy.type=recap_pi \
    --policy.diffusion_repo_id=/home/ubuntu/train_pi/lerobot/outputs/pi05_training_towel/checkpoints/020000/pretrained_model \
    --policy.training_mode=actor \
    --batch_size=64 \
    --steps=1000000 \
    --save_freq=2000 \
    --eval_freq=100000 \
    --wandb.enable=true \
    --wandb.project=lerobot_recap